### ISSUE TITLE
Nested projects are not found

### ISSUE THREAD

**Issue by neissljanik** [nomis51/iis-express-vscode#9]
In my solution, all projects are located in a `src` folder. Since you only check for `.csproj` files that are one level beneath the workspace folder, I can't choose a Starting Project when running the initialize command in my solution folder. For illustration purposes I've included an example of my solution structure below. It would be great if this extension could support nested projects as well.

```txt
my-solution/
├── my-solution.sln
└── src
    ├── my-first-project
    │   └── my-first-project.csproj
    └── my-second-project
        └── my-second-project.csproj
```

**Comment by nomis51** [comment]
I'll take a look

**Comment by nomis51** [comment]
Version [0.1.7](https://github.com/nomis51/iis-express-vscode/releases/tag/v0.1.7) now supports projects below solution level

**Comment by neissljanik** [comment]
Works great, thank you!
